name: Build Svelte using Bun

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Bun
      run: curl -fsSL https://bun.sh/install | bash
    - name: Path Bun
      run: source /home/runner/.bashrc 
    - name: Install Node Dependency
      run: bun install
    - name: Build
      run: bun run build
